--erstelle View
CREATE OR REPLACE VIEW V_KALENDER_GENERATOR AS 
SELECT 
	datum,
	to_char(datum, 'DAY') AS Wochentag,
	to_char(datum, 'MONTH') AS Monat,
	to_char(datum, 'D') AS wochentag_zahl,
	to_char(datum, 'IW') AS iso_woche,
	extract(month from datum) AS monat_zahl,
	extract(year from datum) AS jahr,
	case when to_char(datum, 'D') = 1 then 1 else 0 end AS erster_tag_der_woche,
	case when extract (DAY FROM datum) = 1 then 1 else 0 end AS erster_tag_des_monats
FROM ( 
	SELECT TO_DATE('01.01.2000 ', 'DD.MM.YYYY') + LEVEL -1 AS datum
	FROM dual 
	CONNECT BY LEVEL <= TO_DATE ('31.12.2030', 'DD.MM.YYYY') - TO_DATE('01.01.2000 ', 'DD.MM.YYYY') + 1
);
--select from view
select * from V_KALENDER_GENERATOR
where datum ='22.07.2024';

--erstelle tabelle KALENDER
CREATE TABLE KALENDER 
PARTITION BY RANGE(datum) INTERVAL(NUMTOYMINTERVAL(1, 'YEAR'))
SUBPARTITION BY LIST (monat_zahl)
SUBPARTITION TEMPLATE
(
	SUBPARTITION PRT_MONAT_JAN VALUES (1),
	SUBPARTITION PRT_MONAT_FEB VALUES (2),
	SUBPARTITION PRT_MONAT_MAR VALUES (3),
	SUBPARTITION PRT_MONAT_APR VALUES (4),
	SUBPARTITION PRT_MONAT_MAY VALUES (5),
	SUBPARTITION PRT_MONAT_JUN VALUES (6),
	SUBPARTITION PRT_MONAT_JUL VALUES (7),
	SUBPARTITION PRT_MONAT_AUG VALUES (8),
	SUBPARTITION PRT_MONAT_SEP VALUES (9),
	SUBPARTITION PRT_MONAT_OKT VALUES (10),
	SUBPARTITION PRT_MONAT_NOV VALUES (11),
	SUBPARTITION PRT_MONAT_DEC VALUES (12),
	SUBPARTITION PRT_MONAT_XXX VALUES (default)
)
(
	PARTITION PRT_TEMPLATE_JAHR VALUES LESS THAN ('01.01.2000')
)
AS 
SELECT * FROM V_KALENDER_GENERATOR;

--select from table kalender
SELECT * FROM KALENDER;

--erstelle indexes 
CREATE UNIQUE INDEX UX1_KALENDER ON KALENDER(datum);

CREATE BITMAP INDEX BX2_KALENDER ON KALENDER (WOCHENTAG) LOCAL;

CREATE BITMAP INDEX BX3_KALENDER ON KALENDER (MONAT) LOCAL;

CREATE INDEX IX4_KALENDER ON KALENDER (datum, monat) LOCAL;

CREATE INDEX IX5_KALENDER ON KALENDER (datum, wochentag) LOCAL;

CREATE INDEX IX_6_KALENDER ON KALENDER(UPPER(WOCHENTAG));