DROP TABLE TA_BZULIE_TEST
;

CREATE TABLE TA_BZULIE_TEST
PARTITION BY LIST(REGION)
SUBPARTITION BY LIST(A_BEARBEITUNGSZUSTAND)
SUBPARTITION TEMPLATE(
SUBPARTITION SPRT_TA_BZULIE_TEST1 VALUES ('as') ,
SUBPARTITION SPRT_TA_BZULIE_TEST2 VALUES ('an') ,
SUBPARTITION SPRT_TA_BZULIE_TEST3 VALUES ('om') ,
SUBPARTITION SPRT_TA_BZULIE_TEST4 VALUES ('of') ,
SUBPARTITION SPRT_TA_BZULIE_TEST5 VALUES ('wB') ,
SUBPARTITION SPRT_TA_BZULIE_TEST6 VALUES ('st') ,
SUBPARTITION SPRT_TA_BZULIE_TEST7 VALUES ('ab') ,
SUBPARTITION SPRT_TA_BZULIE_TEST8 VALUES ('TV') ,
SUBPARTITION SPRT_TA_BZULIE_TEST9 VALUES ('PZ','PL') ,
SUBPARTITION SPRT_TA_BZULIE_TEST10 VALUES ('SK','KU','SU') ,
SUBPARTITION SPRT_TA_BZULIE_TEST11 VALUES (DEFAULT) )
(PARTITION PRT_TA_BZULIE_TEST1 VALUES (1) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST2 VALUES (2) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST3 VALUES (3) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST4 VALUES (4) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST5 VALUES (7) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST6 VALUES (9) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST7 VALUES (10) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST8 VALUES (0) NOLOGGING,
PARTITION PRT_TA_BZULIE_TEST9 VALUES (DEFAULT) NOLOGGING)
PARALLEL
NOLOGGING
AS 
SELECT * FROM TA_BZULIE
WHERE A_MODIFIZIERT_ZEITPUNKT < '01.01.2024' -- 37 Sekunden
;
ALTER TABLE TA_BZULIE_TEST NOPARALLEL
;
/*
ALTER TABLE TA_BZULIE_TEST ADD PRIMARY KEY (REGION, A_BZL_LFD_NR) USING INDEX (CREATE INDEX UX1_BZULIE ON TA_BZULIE_TEST(REGION, A_BZL_LFD_NR)) ENABLE NOVALIDATE;

ALTER TABLE TA_BZULIE_TEST MODIFY PRIMARY KEY VALIDATE;
*/

ALTER TABLE TA_BZULIE_TEST ADD CONSTRAINT PK_TA_BZULIE_TEST PRIMARY KEY (REGION, A_BZL_LFD_NR) USING INDEX (CREATE INDEX UX1_BZULIE ON TA_BZULIE_TEST(REGION, A_BZL_LFD_NR) PARALLEL NOLOGGING) ENABLE NOVALIDATE; --32 sekunden
ALTER INDEX UX1_BZULIE NOPARALLEL;
ALTER TABLE TA_BZULIE_TEST MODIFY CONSTRAINT PK_TA_BZULIE_TEST VALIDATE; --33 sekunden


CREATE UNIQUE INDEX UX1_BZULIE ON TA_BZULIE_TEST (REGION, A_BZL_LFD_NR) NOLOGGING PARALLEL; -- 17 Sekunden für Teilmenge
ALTER INDEX UX1_BZULIE NOPARALLEL;
DROP INDEX UX1_BZULIE;

CREATE INDEX IX1_BZULIE_TEST ON TA_BZULIE_TEST (A_AUFTRNR) NOLOGGING PARALLEL; -- 20 Sekunden für Teilmenge
ALTER INDEX IX1_BZULIE_TEST NOPARALLEL;
ALTER INDEX IX1_BZULIE_TEST UNUSABLE;

INSERT INTO /* APPEND PARALLEL(TA_BZULIE_TEST) */ TA_BZULIE_TEST SELECT * FROM TA_BZULIE WHERE A_MODIFIZIERT_ZEITPUNKT >= '01.01.2024'; -- 30 Sekunden mit UNUSABLE INDEX; 3:21 min Index

ALTER INDEX IX1_BZULIE_TEST REBUILD ONLINE PARALLEL; -- 50 Sekunden (OFFLINE)
ALTER INDEX IX1_BZULIE_TEST NOPARALLEL;


DROP INDEX IX1_BZULIE;




CREATE INDEX IX2_BZULIE ON TA_BZULIE_TEST (A_AUFTRNR, A_BEARBEITUNGSZUSTAND) LOCAL PARALLEL;
ALTER INDEX IX2_BZULIE NOPARALLEL;
DROP INDEX IX2_BZULIE;
 


