CREATE TABLE TA_BZULIE_TEST
PARTITION BY LIST(REGION)
SUBPARTITION BY LIST(A_BEARBEITUNGSZUSTAND)
SUBPARTITION TEMPLATE(
SUBPARTITION SPRT_TA_BZULIE_TEST1 VALUES ('as') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST2 VALUES ('an') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST3 VALUES ('om') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST4 VALUES ('of') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST5 VALUES ('wB') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST6 VALUES ('st') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST7 VALUES ('ab') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST8 VALUES ('TV') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST9 VALUES ('PZ','PL') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST10 VALUES ('SK','KU','SU') COMPRESS FOR ALL OPERATIONS,
SUBPARTITION SPRT_TA_BZULIE_TEST11 VALUES (DEFAULT) COMPRESS FOR ALL OPERATIONS)
(PARTITION PRT_TA_BZULIE_TEST1 VALUES (1) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST2 VALUES (2) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST3 VALUES (3) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST4 VALUES (4) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST5 VALUES (7) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST6 VALUES (9) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST7 VALUES (10) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST8 VALUES (0) NOLOGGING COMPRESS FOR ALL OPERATIONS,
PARTITION PRT_TA_BZULIE_TEST9 VALUES (DEFAULT) NOLOGGING)
PARALLEL
NOLOGGING
AS 
SELECT * FROM TA_BZULIE
-- 53 sekunden ohne compress
--WHERE A_MODIFIZIERT_ZEITPUNKT < '01.01.2024' -- 37 Sekunden (36 sec Sasha)
;
ALTER TABLE TA_BZULIE_TEST NOPARALLEL
;
CREATE INDEX IX0_BZULIE_TEST ON TA_BZULIE_TEST(A_MODIFIZIERT_ZEITPUNKT) NOLOGGING PARALLEL;
ALTER INDEX IX0_BZULIE_TEST NOPARALLEL;
ALTER INDEX IX0_BZULIE_TEST UNUSABLE;
;
/*
ALTER TABLE TA_BZULIE_TEST ADD PRIMARY KEY (REGION, A_BZL_LFD_NR) USING INDEX (CREATE INDEX UX1_BZULIE ON TA_BZULIE_TEST(REGION, A_BZL_LFD_NR)) ENABLE NOVALIDATE;

ALTER TABLE TA_BZULIE_TEST MODIFY PRIMARY KEY VALIDATE;
*/

ALTER TABLE TA_BZULIE_TEST ADD CONSTRAINT UC_TA_BZULIE_TEST UNIQUE (REGION, A_BZL_LFD_NR, A_AUFTRNR) USING INDEX (CREATE INDEX UX2_BZULIE ON TA_BZULIE_TEST(REGION, A_BZL_LFD_NR, A_AUFTRNR) PARALLEL NOLOGGING) ENABLE NOVALIDATE; --32 sekunden
ALTER INDEX UX2_BZULIE NOPARALLEL;
ALTER TABLE TA_BZULIE_TEST MODIFY CONSTRAINT UC_TA_BZULIE_TEST VALIDATE; --33 sekunden

/*
CREATE UNIQUE INDEX UX1_BZULIE ON TA_BZULIE_TEST (REGION, A_BZL_LFD_NR) NOLOGGING PARALLEL; -- 17 Sekunden für Teilmenge
ALTER INDEX UX1_BZULIE NOPARALLEL;
DROP INDEX UX1_BZULIE;
*/

CREATE INDEX IX1_BZULIE_TEST ON TA_BZULIE_TEST (A_AUFTRNR) LOCAL NOLOGGING PARALLEL; -- 20 Sekunden für Teilmenge (14 sec Sasha)
ALTER INDEX IX1_BZULIE_TEST NOPARALLEL;
ALTER INDEX IX1_BZULIE_TEST UNUSABLE;

CREATE INDEX IX2_BZULIE_TEST ON TA_BZULIE_TEST (A_BZL_LFD_NR) LOCAL NOLOGGING PARALLEL; --  (12 sec Sasha)
ALTER INDEX IX2_BZULIE_TEST NOPARALLEL;
ALTER INDEX IX2_BZULIE_TEST UNUSABLE;

CREATE INDEX IX3_BZULIE_TEST ON TA_BZULIE_TEST (A_MODIFIZIERT_ZEITPUNKT) LOCAL NOLOGGING PARALLEL; --  (13 sec Sasha)
ALTER INDEX IX3_BZULIE_TEST NOPARALLEL;
ALTER INDEX IX3_BZULIE_TEST UNUSABLE;
DROP INDEX IX3_BZULIE_TEST;



SELECT *
	--index_name, status, index_type, partitioned, uniqueness
FROM user_indexes
WHERE 1=1
	AND INDEX_NAME = 'UX1_BZULIE'
--AND status = 'UNUSABLE'
--AND partitioned = 'YES'
--AND index_type = 'LOCAL'
;
SELECT * FROM user_constraints
WHERE TABLE_NAME = 'TA_BZULIE_TEST';




INSERT INTO /* APPEND PARALLEL(TA_BZULIE_TEST) */ TA_BZULIE_TEST SELECT * FROM TA_BZULIE WHERE A_MODIFIZIERT_ZEITPUNKT >= '01.01.2024'; -- 30 Sekunden mit UNUSABLE INDEX; 3:21 min Index

ALTER INDEX IX1_BZULIE_TEST REBUILD ONLINE PARALLEL; -- 50 Sekunden (OFFLINE)
ALTER INDEX IX1_BZULIE_TEST NOPARALLEL;


DROP INDEX IX1_BZULIE;




CREATE INDEX IX2_BZULIE ON TA_BZULIE_TEST (A_AUFTRNR, A_BEARBEITUNGSZUSTAND) LOCAL PARALLEL;
ALTER INDEX IX2_BZULIE NOPARALLEL;
DROP INDEX IX2_BZULIE;
 
 
 
SELECT *
FROM user_ind_partitions
WHERE 1=1
AND status = 'UNUSABLE'
;

SELECT *
FROM user_ind_subpartitions
WHERE 1=1
AND status = 'UNUSABLE'
;
exec rebuild_indexes_offline(strTable => 'TA_BZULIE_TEST');